apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: hands-on-blue
  labels:
    color: blue
---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: hands-on-yellow
  labels:
    color: yellow
